export const SOCKET_EVENTS = {
    CREATE_ISSUE: 'CREATE_ISSUE',
    UPDATE_ISSUE: 'UPDATE_ISSUE',
    DELETE_ISSUE: 'DELETE_ISSUE',

    CREATE_SPRINT: 'CREATE_SPRINT',
    UPDATE_SPRINT: 'UPDATE_SPRINT',
    DELETE_SPRINT: 'DELETE_SPRINT',

    CREATE_EPIC: 'CREATE_EPIC',
    UPDATE_EPIC: 'UPDATE_EPIC',
    DELETE_EPIC: 'DELETE_EPIC',

    CREATE_COMMENT: 'CREATE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
};
